### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by syzer** [liip/guess-the-liiper-ios#26]
```
ERROR  watch EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"watch"}
Error: watch EMFILE
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at NodeWatcher.watchdir (/js/React/guess-the-liiper-ios/node_modules/react-native/node_modules/sane/src/node_watcher.js:144:20)
    at Walker.<anonymous> (/js/React/guess-the-liiper-ios/node_modules/react-native/node_modules/sane/src/node_watcher.js:351:12)
    at Walker.emit (events.js:110:17)
    at /js/React/guess-the-liiper-ios/node_modules/react-native/node_modules/sane/node_modules/walker/lib/walker.js:69:16
    at /js/React/guess-the-liiper-ios/node_modules/react-native/node_modules/graceful-fs/graceful-fs.js:140:16
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by syzer** [comment]
```
See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
fs.js:565
fs.write = function(fd, buffer, offset, length, position, callback) {
                                                 ^
Error: EMFILE, too many open files '/Users/dasdsa/.babel.json'
```

**Comment by syzer** [comment]
solved by `brew install watchman`
